---
title: "Mini-Project 3"
author: "Emily Liu, Karina Lieb, and Alexis Kilayko"
date: "April 14, 2018"
output: 
  html_document:
    code_folding: hide
---

```{r, message=FALSE, warning=FALSE}
# Loading libraries
library(tidyverse)
library(leaflet)
library(macleish)
library(sf)
library(mapview)
```

```{r, eval = FALSE}
# Downloading contour data, not needed after it was added to GitHub. 
# url <- "http://download.massgis.digital.mass.gov/shapefiles/state/contours250k.zip"
# local_file <- basename(url)
# download.file(url, destfile = local_file)
# unzip(local_file, exdir = "contours250k")
# dsn <- path.expand("contours250k")
# dsn
# list.files(dsn)
# contours <- read_sf(dsn)
# Limiting contour data to within Macleish area
# contours_4326 <- contours %>%
#   st_transform(4326)
# contours_inside <- macleish_layers[["boundary"]] %>%
#   st_intersection(contours_4326)
```

```{r}
# AEA projection scheme for buffers
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
```

```{r}
# Create current campsite points
campsites_pt <- tribble(
  ~point, ~lat, ~lon,
  "Group Campsite", -72.678154, 42.450976,
  "Remote Campsite", -72.679581, 42.458549
)

# Convert campsite points to shapefile
campsites_sf <- campsites_pt %>%
  st_as_sf(coords = c("lat", "lon"))
```

```{r}
# Visually figuring out the forests that the campsites are in
forests <- macleish_layers[["forests"]] %>%
  rename(forest_type = Sheet1__Na)

leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_layers[["boundary"]], weight = 1, color = "black") %>%
  addPolygons(data = forests, weight = 1, color = "green", popup = ~forest_type) %>%
  addMarkers(data = campsites_sf, popup = ~point)

# Create dataset that will only have those types of forests
pine_maple <- forests %>%
  filter(forest_type == "Old Field White Pine Forest" | forest_type == "Sugar Maple Forest")

# Some desirable forests to put campsites near (according to Reid)
oak <- forests %>%
  filter(forest_type == "Red Oak Forest" | forest_type == "Red Oak-Hemlock Forest" | forest_type == "Abandoned Pasture")
```

```{r}
# Create parking point
parking_pt <- tribble(
  ~point, ~lat, ~lon,
  "Parking Lot", -72.680663, 42.448013 
)

# Convert parking point to shapefile and set coordinate system
parking_sf <- parking_pt %>%
  st_as_sf(coords = c("lat", "lon")) %>%
  st_set_crs(4326)

# Create .5 mile buffer zone around parking lot (requirement)
parking_bf <- parking_sf %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 804.672) %>%
  st_transform(crs = 4326)

```

```{r}
# create streams buffer zones, 200 feet = 60.96 m (requirement)
streams_bf <- macleish_layers[["streams"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 60.96) %>%
  st_transform(4326)

# create wetlands buffer zones (requirement)
wetlands_bf <- macleish_layers[["wetlands"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 60.96) %>%
  st_transform(4326)

# create research buffer zones, 500 feet = 152.4 m (restriction)
research_bf <- macleish_layers[["research"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 152.4) %>%
  st_transform(4326)

# create challenge course buffer zones (restriction)
challenge_bf <- macleish_layers[["challenge_courses"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 152.4) %>%
  st_transform(4326)
```

```{r}
# Our proposed campsites
our_camps_pt <- tribble(
  ~point, ~lat, ~lon,
  "Campsite A", -72.68207, 42.44893,
  "Campsite B", -72.67990, 42.44741
)
# Create campsite shapefile
our_camps_sf <- our_camps_pt %>%
  st_as_sf(coords = c("lat", "lon")) %>%
  st_set_crs(4326)

# Create buffer zones to show approx. campsite area (according to Reid)
our_camps_bf <- our_camps_sf %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 3) %>%
  st_transform(4326)
```


```{r}
#creating icons for proposed campsite, current campsite, and parking lot markers
icons <- awesomeIcons(icon = 'glyphicon glyphicon-tent', markerColor = 'orange')
ccicons <- awesomeIcons(icon = 'glyphicon glyphicon-tent', markerColor = 'blue')
caricon <- awesomeIcons(icon = "glyphicon glyphicon-road", markerColor = 'green')

# Make a leaflet map with green zones being our required areas and pink/red zones are our restricted areas
map <- leaflet() %>%
  addTiles() %>%
  # macleish boundary lines
  addPolylines(data = macleish_layers[["boundary"]], weight = 1, group = "Boundary") %>%
  # macleish streams
  addPolylines(data = macleish_layers[["streams"]], weight = 1, color = "blue", group = "Streams") %>%
  # contour lines
  addPolylines(data = macleish_layers[["contours_3m"]], weight = 1, color = "black", group = "Contours") %>%
  # macleish wetlands
  addPolygons(data = macleish_layers[["wetlands"]], color = "blue", opacity = 0.5, group = "Wetlands") %>%
  # draw stream buffer zones
  addPolygons(data = streams_bf, color = "lightgreen", fillColor = "transparent", group = "Streams") %>%
  # draw wetlands buffer zones
  addPolygons(data = wetlands_bf, color = "lightgreen", fillColor = "transparent", group = "Wetlands") %>%
  # draw research buffer zones
  addPolygons(data = research_bf, color = "pink", fillColor = "transparent", group = "Research Area") %>%
  # draw challenge course buffer zones
  addPolygons(data = challenge_bf, color = "pink", fillColor = "transparent", group = "Challenge Course") %>%
  # current campsite markers
  addAwesomeMarkers(data = campsites_sf, popup = ~point, icon = ccicons, group = "Campsites") %>%
  # current campsite forests
  addPolygons(data = pine_maple, weight = 1, color = "red", group = "Forests") %>%
  # good forests to be in (according to Reid)
  addPolygons(data = oak, weight = 1, color = "green", group = "Forests") %>%
  # macleish forests
  addPolygons(data = forests, weight = 1, color = "green", fillColor = "transparent", popup = ~forest_type) %>%
  addPolylines(data = macleish_layers[["trails"]], weight = 2, color = ~color, label = ~name) %>%
  # parking lot marker
  addAwesomeMarkers(data = parking_sf, icon = caricon, popup = ~point) %>%
  # draw parking lot buffer zone (0.5 mile radius)
  addPolygons(data = parking_bf, color = "green", fillColor = "transparent", group = "Parking") %>%
  # proposed campsite markers
  addAwesomeMarkers(data = our_camps_sf, popup = ~point, icon=icons, group = "Campsites") %>%
  # draw approximate size of campsite
  addPolygons(data = our_camps_bf, color = "orange", group = "Campsites") %>%
  # add map tool that will display coordinates of point that mouse is over
  addMouseCoordinates() %>%
#adding layer controls
  addLayersControl(overlayGroups = c("Boundary", "Streams", "Contours", "Wetlands", "Research Area", "Challenge Course", "Forests", "Parking", "Campsites"), options = layersControlOptions(collapsed = FALSE)) %>%
  addScaleBar()
map  
```


```{r}
# Map of attractions around the campsites
map2 <- leaflet() %>%
  addTiles() %>%
  # macleish boundary
  addPolylines(data = macleish_layers[["boundary"]], color = "black", weight = 1, opacity = 0.5, group = "Boundary") %>%
  # macleish streams
  addPolylines(data = macleish_layers[["streams"]], color = "blue", weight = 2, group = "Streams and Wetlands") %>%
  # macleish wetlands
  addPolygons(data = macleish_layers[["wetlands"]], weight = 2, group = "Streams and Wetlands") %>%
  # macleish forests
  addPolygons(data = forests, weight = 1, color = "transparent", fillColor = "transparent", popup = ~forest_type) %>%
  # macleish trails
  addPolylines(data = macleish_layers[["trails"]], weight = 2, color = ~color, label = ~name, group = "Trails") %>%
  # macleish landmarks
  addMarkers(data = macleish_layers[["landmarks"]], popup = ~Label, group = "Landmarks") %>%
  # parking lot marker
  addAwesomeMarkers(data = parking_sf, popup = ~point, icon = caricon, group = "Parking Lot") %>%
  addScaleBar()%>%
  # proposed campsite markers
  addAwesomeMarkers(data = our_camps_sf, popup = ~point, icon=icons, group = "Campsites") %>%
  # draw approximate size of campsite
  addPolygons(data = our_camps_bf, color = "orange", group = "Campsites")%>%
  addAwesomeMarkers(data = campsites_sf, popup = ~point, icon = ccicons, group = "Campsites") %>%
  #adding layer controls
  addLayersControl(overlayGroups = c("Boundary", "Streams and Wetlands", "Trails", "Landmarks", "Parking Lot", "Campsites"), options = layersControlOptions(collapsed = FALSE)) 

map2
```